import { svelte } from '@sveltejs/vite-plugin-svelte';
import tailwindcss from '@tailwindcss/vite';
import { builtinModules } from 'module';
import { defineConfig } from 'vite';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY VITE
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.env.NODE_ENV === 'production';

export default defineConfig({
    plugins: [
        tailwindcss(),
        svelte({
            compilerOptions: {
                css: 'external',
                runes: true,
            },
        }),
    ],
    build: {
        lib: {
            entry: 'main.ts',
            formats: ['cjs'],
            fileName: () => 'main.js',
        },
        outDir: './',
        emptyOutDir: false,
        sourcemap: prod ? false : 'inline',
        minify: prod,
        target: 'es2018',
        copyPublicDir: false,
        rollupOptions: {
            external: [
                'obsidian',
                'electron',
                '@codemirror/autocomplete',
                '@codemirror/collab',
                '@codemirror/commands',
                '@codemirror/language',
                '@codemirror/lint',
                '@codemirror/search',
                '@codemirror/state',
                '@codemirror/view',
                '@lezer/common',
                '@lezer/highlight',
                '@lezer/lr',
                ...builtinModules,
                ...builtinModules.map((m) => `node:${m}`),
            ],
            output: {
                format: 'cjs',
                exports: 'default',
                banner,
                // 确保 CSS 文件名
                assetFileNames: (assetInfo) => {
                    if (assetInfo.name?.endsWith('.css')) {
                        return 'styles.css';
                    }
                    return assetInfo.name || 'assets/[name][extname]';
                },
            },
        },
    },
    resolve: {
        alias: {
            $lib: '/src/lib',
        },
        conditions: ['svelte', 'browser', 'default', 'import', 'module'],
    },
});
